# Generated by Django 2.0.4 on 2018-04-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('raza_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_animal', models.CharField(blank=True, choices=[('asd', 'as')], max_length=100, null=True)),
                ('peso_animal', models.IntegerField(blank=True, null=True)),
                ('edad_animal', models.IntegerField(blank=True, null=True)),
                ('foto_animal', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
